### ISSUE TITLE
Search bar is not clear it's a search bar

### ISSUE THREAD

**Issue by DragonBe** [in2it-training/phpbootcamp-shop-talent-it-march-2017#2]
The design of the search bar makes it a bit hard to understand it's ment for searching. A small but significant improvement would be to change the text "Go" into "Search"

![screenshot 2017-03-04 23 24 11](https://cloud.githubusercontent.com/assets/282825/23582760/bc7ac4ac-0131-11e7-9f67-2e052a8110af.png)

**Comment by jressen** [comment]
done!

**Comment by DragonBe** [comment]
@jressen bedankt voor de update, maar ik ga het issue nog even heropenen totdat jouw changes via pull requests terug in the blessed repository zijn gezet.

**Comment by DragonBe** [comment]
Issue is solved and merged in PR #7
